version: "3"

services:
  application:
    image: gobarber
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file: .env
    links:
      - postgre
    container_name: application

  postgre:
    image: kartoza/postgis
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgreSQL_data:/var/lib/postgresql
    container_name: dbpostgre
