version: "3"

services:
  application:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file: .env
    links:
      - postgres
    container_name: application

  postgres:
    image: kartoza/postgis
    env_file: .env
    ports:
      - "5432:5432"
    container_name: dbpostgres
